openapi: 3.0.3
info:
  title: REST API
  description: API for group events
  version: 0.1.1
externalDocs:
  description: "JSONPlaceholder's guide"
  url: https://jsonplaceholder.typicode.com/guide
servers:
- url: http://localhost:3000
  description: Main
paths:
  "/contact":
    get:
      tags: ["contact"]
      summary: Все контакты
    post:
      tags: ["contact"]
      summary: Добавить контакты
    